# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from pirogue_admin_api import access_pb2 as pirogue__admin__api_dot_access__pb2


class AccessStub(object):
    """
    Manage accesses to this PiRogue.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetAdministrationToken = channel.unary_unary(
                '/pirogue.admin.access.Access/ResetAdministrationToken',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.GetAdministrationToken = channel.unary_unary(
                '/pirogue.admin.access.Access/GetAdministrationToken',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.GetAdministrationCertificate = channel.unary_unary(
                '/pirogue.admin.access.Access/GetAdministrationCertificate',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.GetAdministrationCLIs = channel.unary_unary(
                '/pirogue.admin.access.Access/GetAdministrationCLIs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.CreateUserAccess = channel.unary_unary(
                '/pirogue.admin.access.Access/CreateUserAccess',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
                )
        self.GetUserAccess = channel.unary_unary(
                '/pirogue.admin.access.Access/GetUserAccess',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
                )
        self.ListUserAccesses = channel.unary_unary(
                '/pirogue.admin.access.Access/ListUserAccesses',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.UserAccessList.FromString,
                )
        self.DeleteUserAccess = channel.unary_unary(
                '/pirogue.admin.access.Access/DeleteUserAccess',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ResetUserAccessToken = channel.unary_unary(
                '/pirogue.admin.access.Access/ResetUserAccessToken',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
                )
        self.GetPermissionList = channel.unary_unary(
                '/pirogue.admin.access.Access/GetPermissionList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.ServiceAccess.FromString,
                )
        self.SetUserAccessPermissions = channel.unary_unary(
                '/pirogue.admin.access.Access/SetUserAccessPermissions',
                request_serializer=pirogue__admin__api_dot_access__pb2.PermissionChanges.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
                )


class AccessServicer(object):
    """
    Manage accesses to this PiRogue.
    """

    def ResetAdministrationToken(self, request, context):
        """
        Resets and generate a new administration token.
        Returns the new administration token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdministrationToken(self, request, context):
        """
        Get the current administration token.
        Returns the current administration token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdministrationCertificate(self, request, context):
        """
        Get the current administration certificate.
        Returns the current administration certificate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdministrationCLIs(self, request, context):
        """
        Get a command line set to execute to configure a new remote client.
        Returns command line instructions in one string
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserAccess(self, request, context):
        """
        Create a new user access with a fresh token and a empty access list.
        Returns the newly created UserAccess.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAccess(self, request, context):
        """
        Get user access details given its integer ID.
        Params: the user access integer ID.
        Returns the request UserAccess if it exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserAccesses(self, request, context):
        """
        Get a user access list.
        Returns the UserAccess list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserAccess(self, request, context):
        """
        Delete a user access given its integer ID.
        Params: the user access integer ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetUserAccessToken(self, request, context):
        """
        Reset the token a specific user access given its integer ID.
        Returns the UserAccess with its new token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPermissionList(self, request, context):
        """
        Get a dictionary of all available permissions.
        Returns the ServiceAccess dictionary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUserAccessPermissions(self, request, context):
        """
        Set a batch of permissions changes for the given user access ID.
        Changes may be a list of 'set', 'add' or 'remove'.
        Returns the updated UserAccess.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetAdministrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetAdministrationToken,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'GetAdministrationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdministrationToken,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'GetAdministrationCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdministrationCertificate,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'GetAdministrationCLIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdministrationCLIs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'CreateUserAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserAccess,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.UserAccess.SerializeToString,
            ),
            'GetUserAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAccess,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.UserAccess.SerializeToString,
            ),
            'ListUserAccesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserAccesses,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.UserAccessList.SerializeToString,
            ),
            'DeleteUserAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserAccess,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ResetUserAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetUserAccessToken,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.UserAccess.SerializeToString,
            ),
            'GetPermissionList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPermissionList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.ServiceAccess.SerializeToString,
            ),
            'SetUserAccessPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUserAccessPermissions,
                    request_deserializer=pirogue__admin__api_dot_access__pb2.PermissionChanges.FromString,
                    response_serializer=pirogue__admin__api_dot_access__pb2.UserAccess.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pirogue.admin.access.Access', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Access(object):
    """
    Manage accesses to this PiRogue.
    """

    @staticmethod
    def ResetAdministrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/ResetAdministrationToken',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAdministrationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/GetAdministrationToken',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAdministrationCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/GetAdministrationCertificate',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAdministrationCLIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/GetAdministrationCLIs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/CreateUserAccess',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/GetUserAccess',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserAccesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/ListUserAccesses',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_access__pb2.UserAccessList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/DeleteUserAccess',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetUserAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/ResetUserAccessToken',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPermissionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/GetPermissionList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_access__pb2.ServiceAccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetUserAccessPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.access.Access/SetUserAccessPermissions',
            pirogue__admin__api_dot_access__pb2.PermissionChanges.SerializeToString,
            pirogue__admin__api_dot_access__pb2.UserAccess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
