# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from pirogue_admin_api import network_pb2 as pirogue__admin__api_dot_network__pb2


class NetworkStub(object):
    """
    Manage network related features on this PiRogue.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListVPNPeers = channel.unary_unary(
                '/pirogue.admin.network.Network/ListVPNPeers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.VPNPeerList.FromString,
                )
        self.GetVPNPeer = channel.unary_unary(
                '/pirogue.admin.network.Network/GetVPNPeer',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
                )
        self.GetVPNPeerConfig = channel.unary_unary(
                '/pirogue.admin.network.Network/GetVPNPeerConfig',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.AddVPNPeer = channel.unary_unary(
                '/pirogue.admin.network.Network/AddVPNPeer',
                request_serializer=pirogue__admin__api_dot_network__pb2.VPNPeerAddRequest.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
                )
        self.DeleteVPNPeer = channel.unary_unary(
                '/pirogue.admin.network.Network/DeleteVPNPeer',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
                )
        self.GetWifiConfiguration = channel.unary_unary(
                '/pirogue.admin.network.Network/GetWifiConfiguration',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.WifiConfiguration.FromString,
                )
        self.SetWifiConfiguration = channel.unary_unary(
                '/pirogue.admin.network.Network/SetWifiConfiguration',
                request_serializer=pirogue__admin__api_dot_network__pb2.WifiConfiguration.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.EnableExternalPublicAccess = channel.unary_unary(
                '/pirogue.admin.network.Network/EnableExternalPublicAccess',
                request_serializer=pirogue__admin__api_dot_network__pb2.PublicAccessRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DisableExternalPublicAccess = channel.unary_unary(
                '/pirogue.admin.network.Network/DisableExternalPublicAccess',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.OpenIsolatedPort = channel.unary_unary(
                '/pirogue.admin.network.Network/OpenIsolatedPort',
                request_serializer=pirogue__admin__api_dot_network__pb2.IsolatedPort.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CloseIsolatedPort = channel.unary_unary(
                '/pirogue.admin.network.Network/CloseIsolatedPort',
                request_serializer=pirogue__admin__api_dot_network__pb2.ClosePortRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListIsolatedOpenPorts = channel.unary_unary(
                '/pirogue.admin.network.Network/ListIsolatedOpenPorts',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pirogue__admin__api_dot_network__pb2.IsolatedPortList.FromString,
                )


class NetworkServicer(object):
    """
    Manage network related features on this PiRogue.
    """

    def ListVPNPeers(self, request, context):
        """
        Get a list of active VPN peers.
        Returns a list of VPNPeer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVPNPeer(self, request, context):
        """
        Get details about a given VPN peer ID.
        Returns the VPNPeer details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVPNPeerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddVPNPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVPNPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWifiConfiguration(self, request, context):
        """
        Get current WiFi configuration.
        Returns a WifiConfiguration dictionary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWifiConfiguration(self, request, context):
        """
        Set a new WiFi configuration.
        Params: the WifiConfiguration dictionary to use as new configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableExternalPublicAccess(self, request, context):
        """External access 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableExternalPublicAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenIsolatedPort(self, request, context):
        """'Firewall' 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseIsolatedPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIsolatedOpenPorts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListVPNPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVPNPeers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.VPNPeerList.SerializeToString,
            ),
            'GetVPNPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVPNPeer,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.VPNPeer.SerializeToString,
            ),
            'GetVPNPeerConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVPNPeerConfig,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'AddVPNPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVPNPeer,
                    request_deserializer=pirogue__admin__api_dot_network__pb2.VPNPeerAddRequest.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.VPNPeer.SerializeToString,
            ),
            'DeleteVPNPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVPNPeer,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.VPNPeer.SerializeToString,
            ),
            'GetWifiConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWifiConfiguration,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.WifiConfiguration.SerializeToString,
            ),
            'SetWifiConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWifiConfiguration,
                    request_deserializer=pirogue__admin__api_dot_network__pb2.WifiConfiguration.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'EnableExternalPublicAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableExternalPublicAccess,
                    request_deserializer=pirogue__admin__api_dot_network__pb2.PublicAccessRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DisableExternalPublicAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableExternalPublicAccess,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OpenIsolatedPort': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenIsolatedPort,
                    request_deserializer=pirogue__admin__api_dot_network__pb2.IsolatedPort.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CloseIsolatedPort': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseIsolatedPort,
                    request_deserializer=pirogue__admin__api_dot_network__pb2.ClosePortRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListIsolatedOpenPorts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIsolatedOpenPorts,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pirogue__admin__api_dot_network__pb2.IsolatedPortList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pirogue.admin.network.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """
    Manage network related features on this PiRogue.
    """

    @staticmethod
    def ListVPNPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/ListVPNPeers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_network__pb2.VPNPeerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVPNPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/GetVPNPeer',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVPNPeerConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/GetVPNPeerConfig',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddVPNPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/AddVPNPeer',
            pirogue__admin__api_dot_network__pb2.VPNPeerAddRequest.SerializeToString,
            pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVPNPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/DeleteVPNPeer',
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            pirogue__admin__api_dot_network__pb2.VPNPeer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWifiConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/GetWifiConfiguration',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_network__pb2.WifiConfiguration.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWifiConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/SetWifiConfiguration',
            pirogue__admin__api_dot_network__pb2.WifiConfiguration.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableExternalPublicAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/EnableExternalPublicAccess',
            pirogue__admin__api_dot_network__pb2.PublicAccessRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableExternalPublicAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/DisableExternalPublicAccess',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenIsolatedPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/OpenIsolatedPort',
            pirogue__admin__api_dot_network__pb2.IsolatedPort.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseIsolatedPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/CloseIsolatedPort',
            pirogue__admin__api_dot_network__pb2.ClosePortRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListIsolatedOpenPorts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pirogue.admin.network.Network/ListIsolatedOpenPorts',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pirogue__admin__api_dot_network__pb2.IsolatedPortList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
